# Generated by Django 2.1.5 on 2019-01-30 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountsapp', '0003_auto_20190130_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteeruser',
            name='enrolled_Organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='volunteers', to='accountsapp.OrganizationUser', to_field='organization_Name'),
        ),
    ]
