# Generated by Django 2.1.5 on 2019-01-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_auto_20190130_2026'),
        ('accountsapp', '0005_auto_20190130_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationuser',
            name='operation',
            field=models.ManyToManyField(blank=True, related_name='organizations', to='operations.Operation'),
        ),
        migrations.AddField(
            model_name='volunteeruser',
            name='operation',
            field=models.ManyToManyField(blank=True, related_name='volunteers', to='operations.Operation'),
        ),
    ]
