# Generated by Django 2.1.5 on 2019-01-31 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsapp', '0006_auto_20190130_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationuser',
            name='profilePicture',
            field=models.ImageField(default='../static/img/default.jpg', upload_to='organizations/', verbose_name='Profile Picture'),
        ),
        migrations.AddField(
            model_name='volunteeruser',
            name='profilePicture',
            field=models.ImageField(default='../static/img/default.jpg', upload_to='volunteers/', verbose_name='Profile Picture'),
        ),
    ]
