# Generated by Django 2.1.5 on 2019-01-31 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsapp', '0008_auto_20190131_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationuser',
            name='profilePicture',
            field=models.ImageField(default='default.jpg', upload_to='organizations/', verbose_name='Profile Picture'),
        ),
    ]
