# Generated by Django 2.1.5 on 2019-01-30 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accountsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operationName', models.CharField(max_length=30, unique=True, verbose_name='Operation Name')),
                ('location', models.CharField(max_length=255, unique=True)),
                ('volunteersAssigned', models.IntegerField(default=0, verbose_name='Total Volunteers in the area')),
                ('volunteersInitial', models.IntegerField(verbose_name='Estimated number of required volunteers')),
                ('volunteersRequired', models.IntegerField()),
                ('organization', models.ManyToManyField(related_name='operations', to='accountsapp.OrganizationUser')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UrgencyLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urgency', models.CharField(max_length=50, unique=True)),
                ('urgencyScale', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='operation',
            name='tasks',
            field=models.ManyToManyField(related_name='_operation_tasks_+', to='operations.Task'),
        ),
        migrations.AddField(
            model_name='operation',
            name='urgencyLevel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='operations.UrgencyLevel', verbose_name='Urgency Level'),
        ),
        migrations.AddField(
            model_name='operation',
            name='volunteer',
            field=models.ManyToManyField(related_name='operations', to='accountsapp.VolunteerUser'),
        ),
    ]
