# Generated by Django 2.1.5 on 2019-01-28 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='citizenship_Number',
            field=models.BigIntegerField(blank=True),
        ),
    ]
