# Generated by Django 2.1.5 on 2019-01-30 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operation',
            old_name='task',
            new_name='tasks',
        ),
        migrations.AlterField(
            model_name='operation',
            name='volunteersAssigned',
            field=models.IntegerField(default=0, verbose_name='Total Volunteers in the area'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='volunteersRequired',
            field=models.IntegerField(verbose_name='Estimated number of required volunteers'),
        ),
        migrations.DeleteModel(
            name='VolunteerAssigned',
        ),
        migrations.DeleteModel(
            name='VolunteerRequired',
        ),
    ]
