# Generated by Django 2.1.5 on 2019-01-30 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='volunteersInitial',
            field=models.IntegerField(verbose_name='Estimated Number of Required Volunteers'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='volunteersRequired',
            field=models.IntegerField(verbose_name='Currently Required Number'),
        ),
    ]
