# Generated by Django 2.1.5 on 2019-01-28 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_auto_20190128_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='contact_Number',
            field=models.BigIntegerField(blank=True),
        ),
    ]
