# Generated by Django 2.1.5 on 2019-01-30 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_auto_20190130_0901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='tasks',
        ),
        migrations.AddField(
            model_name='operation',
            name='tasks',
            field=models.ManyToManyField(related_name='_operation_tasks_+', to='operations.Task'),
        ),
    ]
