# Generated by Django 2.1.5 on 2019-01-30 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_auto_20190130_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='organization',
            field=models.ManyToManyField(blank=True, related_name='operations', to='accountsapp.OrganizationUser'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='volunteer',
            field=models.ManyToManyField(blank=True, related_name='operations', to='accountsapp.VolunteerUser'),
        ),
    ]
