# Generated by Django 2.1.5 on 2019-01-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_auto_20190128_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='citizenship_Number',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='contact_Number',
            field=models.BigIntegerField(),
        ),
    ]
