# Generated by Django 2.1.5 on 2019-01-30 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_auto_20190130_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='volunteersRequired',
            field=models.IntegerField(default=0, verbose_name='Currently Required Number'),
        ),
    ]
