# Generated by Django 2.1.5 on 2019-01-30 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_auto_20190130_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='volunteer',
        ),
    ]
