# Generated by Django 2.1.5 on 2019-01-31 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_auto_20190130_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='urgencyLevel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='operations.UrgencyLevel', to_field='urgency', verbose_name='Urgency Level'),
        ),
    ]
